### ISSUE TITLE
running problem

### ISSUE THREAD

**Issue by Afftar123** [natj/runko#46]
Hello!
I've installed runko and tried to run some test simulations (i.e. shock_mini), but when I use
mpirun -n 1 python3 pic.py --conf shock_mini.ini
I get this error

Traceback (most recent call last):
  File "/home/afftar/Documents/runko/projects/pic-shocks/pic.py", line 14, in <module>
    from problem import Configuration_Problem as Configuration
  File "/home/afftar/Documents/runko/projects/pic-shocks/problem.py", line 3, in <module>
    from pytools import Configuration
ImportError: cannot import name 'Configuration' from 'pytools' (/home/afftar/.local/lib/python3.9/site-packages/pytools/__init__.py)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[41289,1],0]
  Exit code:    1

Using more cores change nothing. How can I fix it? Thanks in advance

**Comment by natj** [comment]
Seems to be a path export issue. Probably you are missing this step:

```
export RUNKO=/path2repo
export PYTHONPATH=$PYTHONPATH:$RUNKO
... and rest of the directories...
```
See that it works by printing the PYTHONPATH:
```
>>> import pyrunko
>>>
>>> import os
>>> os.environ['PYTHONPATH'].split(os.pathsep)
['', '/home/natj/runko/', '/home/natj/runko/lib', '/home/natj/runko/corgi/lib', '/home/natj/runko/bindings/old',]
>>>
>>> from pytools import Configuration
>>> 
```

**Comment by Afftar123** [comment]
I didn't miss this spet, I'm sure about it. Now about PYTHONPATH. 
With `import pyrunko` i get

```
Traceback (most recent call last):
  File "/home/afftar/Documents/runko/file.py", line 1, in <module>
    import pyrunko
ModuleNotFoundError: No module named 'pyrunko'
```

with
```
import os
os.environ['PYTHONPATH'].split(os.pathsep)
```
I get
```
Traceback (most recent call last):
  File "/home/afftar/Documents/runko/file.py", line 2, in <module>
    os.environ['PYTHONPATH'].split(os.pathsep)
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'PYTHONPATH'

```
and with the last `from pytools import Configuration`

```
Traceback (most recent call last):
  File "/home/msdos4/Documents/runko/file.py", line 1, in <module>
    from pytools import Configuration
  File "/home/msdos4/Documents/runko/pytools/__init__.py", line 7, in <module>
    from .load_grid import *
  File "/home/msdos4/Documents/runko/pytools/load_grid.py", line 6, in <module>
    import pycorgi
ModuleNotFoundError: No module named 'pycorgi'

```

**Comment by Afftar123** [comment]
I didn't miss this spet, I'm sure about it. Now about PYTHONPATH. 
With `import pyrunko` i get

```
Traceback (most recent call last):
  File "/home/afftar/Documents/runko/file.py", line 1, in <module>
    import pyrunko
ModuleNotFoundError: No module named 'pyrunko'
```

with
```
import os
os.environ['PYTHONPATH'].split(os.pathsep)
```
I get
```
Traceback (most recent call last):
  File "/home/afftar/Documents/runko/file.py", line 2, in <module>
    os.environ['PYTHONPATH'].split(os.pathsep)
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'PYTHONPATH'

```
and with the last `from pytools import Configuration`

```
Traceback (most recent call last):
  File "/home/afftar/Documents/runko/file.py", line 1, in <module>
    from pytools import Configuration
  File "/home/afftar/Documents/runko/pytools/__init__.py", line 7, in <module>
    from .load_grid import *
  File "/home/afftar/Documents/runko/pytools/load_grid.py", line 6, in <module>
    import pycorgi
ModuleNotFoundError: No module named 'pycorgi'

```

**Comment by natj** [comment]
The `PYTHONPATH` environment variable is broken. Typically there is a typo somewhere in the exporting or it was empty when you started (which it typically should not be) so the leading `:` character breaks it.

See e.g., https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path

try printing it with
```
echo $PYTHONPATH
```
before and after you alter it with runko directories. In case it was empty the solution is to change the export to

```
export RUNKO=/path2repo
export PYTHONPATH=$RUNKO
export PYTHONPATH=$PYTHONPATH:$RUNKO/lib
export PYTHONPATH=$PYTHONPATH:$RUNKO/corgi/lib
export PYTHONPATH=$PYTHONPATH:$RUNKO/bindings/old
```
Note how the first export does not have `$PYTHONPATH:` that in case of an empty path would leave an unwanted `:`.

Alternatively you might have virtualenv/anaconda/similar messing with your python3 paths. I suggest using a clean `python3` and installing the packages yourself.

**Comment by Afftar123** [comment]
TY, now it works. The problem seems to be that $PYTHONPATH cleans after I close the terminal and I have to do
```
export RUNKO=/path2repo
export PYTHONPATH=$RUNKO
export PYTHONPATH=$PYTHONPATH:$RUNKO/lib
export PYTHONPATH=$PYTHONPATH:$RUNKO/corgi/lib
export PYTHONPATH=$PYTHONPATH:$RUNKO/bindings/old
```
each time

But ok, now the simulation works. One more question. Now I want to plot the collisionless shock using
`python3 plot_shock.py --conf shock_mini.ini`
but get
```
plotting out-mini/
no analysis file found...
--------------------------------------------------
reading out-mini/flds_0.h5
Traceback (most recent call last):
  File "/home/afftar/Documents/runko/projects/pic-shocks/plot_shock.py", line 80, in read_var
    val = f5F[var][:,:,0]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/afftar/.local/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 780, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/afftar/.local/lib/python3.9/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 107, in h5py._selector.Selector.apply_args
ValueError: 3 indexing arguments for 1 dimensions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/afftar/Documents/runko/projects/pic-shocks/plot_shock.py", line 701, in <module>
    im1, cb1 = plot2d_shock_single(axs[0], "rho", info, do_prtcls=do_prtcls)
  File "/home/afftar/Documents/runko/projects/pic-shocks/plot_shock.py", line 286, in plot2d_shock_single
    val = read_var(f5F, var)
  File "/home/afftar/Documents/runko/projects/pic-shocks/plot_shock.py", line 82, in read_var
    nx = f5F['Nx'].value
AttributeError: 'Dataset' object has no attribute 'value'
```

**Comment by natj** [comment]
Issue is general UNIX behavior. That is why the bashrc/bash_profile is recommended to be updated in the guide.

Second issue a h5py version difference. Replace all `f5['x'].value` with the new `f5['x'][()]` syntax.

I will go ahead and close this because it is not an issue with the code or the installation guide text.
